name: Generate Snake

on:
  schedule:
    # 매일 새벽 12시에 실행
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # github_user_name은 GitHub 사용자 이름으로 설정해야 합니다.
          github_user_name: Youkamii
          output: ./github-contribution-grid-snake.svg

      - name: Commit and Push
        run: |
          git config --global user.name 'Your GitHub Username'
          git config --global user.email 'gkfkd747@naver.com'
          git add -f github-contribution-grid-snake.svg
          git commit -m "Generate snake"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
