name: generate animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Youkamii
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Configure Git
        run: |
          git config --global user.email "gkfkd747@naver.com"
          git config --global user.name "Youkamii"

      - name: Checkout gh-pages branch
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git clone --depth 1 --branch gh-pages https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/Youkamii/Youkamii.git gh-pages

      - name: Copy generated files to gh-pages
        run: |
          cp -r dist/* gh-pages/
          cd gh-pages
          git add .
          git commit -m "Update GitHub contribution grid snake"
          git push origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
